;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname |Esercizio 1|) (read-case-sensitive #t) (teachpacks ((lib "drawings.ss" "installed-teachpacks"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "drawings.ss" "installed-teachpacks")) #f)))
(define josephus                   ; val: etichetta [intero]
  (lambda (n)                      ; n: intero positivo
    (count (new-round-table n))
    ))

(define count                      ; val: etichetta
  (lambda (tab)                    ; tab: configurazione
    (if (last-knight-in? tab)
        (knight-with-jug-in tab)
        (count (after-next-exit-from tab))
        )
    ))

(define new-round-table
  (lambda (n)
    (lambda (x) (+ (remainder x n) 1))
    ))

(define last-knight-in?
  (lambda (tab)
    (let ( (j (tab 0)) )
      (= j (tab j))
      )
    ))

(define knight-with-jug-in
  (lambda (tab)
    (tab 0)
    ))

(define after-next-exit-from
  (lambda (tab)
    (let ( (j (tab 0)) )
      (lambda (x)
        (if (or (= x 0) (= x j))
            (tab (tab j))
            (tab x)
            ))
      )
    ))

(josephus 1)
(josephus 2)
(josephus 3)
(josephus 4)
(josephus 5)
(josephus 6)
(josephus 7)
(josephus 8)
(josephus 9)
(josephus 10)
(josephus 11)
(josephus 12)
(josephus 13)
(josephus 14)
(josephus 15)
(josephus 16)
(josephus 17)
(josephus 18)
(josephus 19)
(josephus 20)
(josephus 21)
(josephus 22)
(josephus 23)
(josephus 24)
(josephus 25)
(josephus 26)
(josephus 27)
(josephus 28)
(josephus 29)
(josephus 30)
(josephus 31)
(josephus 32)
(josephus 33)
(josephus 34)
(josephus 35)
(josephus 36)
(josephus 37)
(josephus 38)
(josephus 39)
(josephus 40)
(josephus 41)
(josephus 42)
(josephus 43)
(josephus 44)
(josephus 45)
(josephus 46)
(josephus 47)
(josephus 48)
(josephus 49)
(josephus 50)